<?php

namespace AppBundle\Repository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
  function all(){

    $test = $this->createQueryBuilder('a');
    $query = $test->getQuery()->getResult();
    return $query;
  }
}
